services:
    twitterwidget.widgetoptions:
        class: TwitterWidgets\Options\WidgetOptions

    twitterwidget.timelinebuilder:
            class: TwitterWidgets\Timeline\TimelineBuilder
            arguments: [@twitterwidget.widgetoptions]

    twitterwidget.timeline:
        class:     TwitterWidgetBundle\Extension\TimelineWidget
        arguments: [@twitterwidget.widgetoptions, @twitterwidget.timelinebuilder]
        tags:
            -  { name: twig.extension }

    twitterwidget.onetimejs:
        class:     TwitterWidgetBundle\Extension\OneTimeJs
        tags:
            -  { name: twig.extension }

