before_commands:
    - "composer update --prefer-source"

tools:
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            excluded_paths: ["vendor/*","Resources/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["Tests", "vendor","Resources"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            excluded_paths: ["vendor/*","Resources/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["Tests", "vendor", "Resources"]
    php_mess_detector:
        enabled: true
        filter:
            excluded_paths: ["vendor/*","Resources/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["Tests", "vendor", "Resources"]
    php_analyzer:
        enabled: true
        filter:
            excluded_paths: ["vendor/*","Resources/*"]
    sensiolabs_security_checker: true
