before_commands:
    - "composer update --prefer-source"

tools:
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
    php_cpd:
        enabled: true
        excluded_dirs: ["Tests", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        excluded_dirs: ["vendor"]
    php_loc:
        enabled: true
        excluded_dirs: ["Tests", "vendor"]
    php_mess_detector:
        enabled: true
        excluded_dirs: ["Tests", "vendor"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["Tests", "vendor"]
    php_analyzer:
        enabled: true
        excluded_dirs: ["vendor"]
    sensiolabs_security_checker: true
